using UnityEngine;

public static class NicknameGenerator
{
    private static readonly string[] oneWordNicks = 
    {
        "the lord", 
        "dek",	
        "NeZoX",	
        "_MaRiXyAnA_",	
        "Jlou_uTep",	
        "Носок судьбы",	
        "Lemonik",	
        "Утка_в_тапках",	
        "Fluffy",	
        "FINISH",	
        "Mr. Zadrot",	
        "NigGa",	
        "He}I{g@Huk",	 
        "JoKeR :D",	
        "Agressor",	
        "AnGeL",	
        "KiSS_Ka",	 
        "KoTuk",
        "CJIoHuK",	 	
        "IceStorm",
        "DoNaTk",	
        "Sa[Y]reX", 
        "WzarD",
        "_LegenDa_", 
        "LIJyXeP",	
        "KukU EpTA",
        "Vitaminka",
        "dvdblueceo",
        "Red_Wolf_",
        "N.E.O.N",	
        "ShOoTeR",
        "Haker",
        "aHoa",
        "CmeTanKa", 
        "AliceFox",
        "Mirrox",	
        "Nessa",
        "Lиsичк", 	
        "AimK",
        "JIuMoHeG", 	
        "SmoKKeR",	
        "ZikZak",
        "N.E.V.E.N", 	
        "Cemeka",
        "Beep",	
        "Enigma",	
        "DIVERSANT",
        "Cherry",
        "Good_Joker", 
        "Fun",
        "АНТИ ПЕТУХ",
        "LiMonk",
        "HarDcore",
        "MANDARIN",
        "çМePтѢ",
        "KyKyPya",
        "XuMuK",
        "Эрагон",
        "Rocket",
        "snakesocks",
        "Magic",
        "Revers",
        "RUDI",
        "Cherry_Pie",
        "-kFFe-",
        "JIou_uTeP", 
        "K_I_N_G",	 
        "Alpha",
        "FeLix",
        "Black_Wolf",
        "Queenie",
        "SkILLzAr",	
        "GaRDeX",
        "MiNi_ZLoB@", 
        "Hanter",
        "Fantasy",
        "FeNiKs",	 
        "FoXy",
        "DEADSHOT", 
        "locJleDHuu",	
        "MamBa",
        "MaxTheGamer", 	
        "Дед", 
        "Сherry",
        "Bambi",
        "Magomed",
        "VeroN", 	
        "СТАРЫЙ ДРУГ",
        "НУБОкиплер",
        "mQ",
        "Чучундра",	
        "kefir",
        "Fire fly",
        "SIREX",
        "Slasher", 	
        "GADZILO",	
        "Палач",
        "Doc",
        "STANIK",
        "Mr. Zamo", 	
        "Bubbly",
        "ArTeMk@",
        "JIoBeK",	
        "Klaimmor", 
        "NyanCat",
        "Я_вернулась",	
        "Ezios",
        "Nlen",
        "RedHulk", 
        "Sweetheart", 
        "JayS",
        "T'ma",
        "DaniLOVE",
        "theWay",
        "trup",
        "010100100",
        "TauRus", 
        "Bella",
        "FrizYT",
        "Нарколог", 	
        "assassin",
        "Barmaley",	
        "Teнь",
        "Doctor", 	
        "Jasper",
        "Skrill",
        "ZeFir",
        "ШИПОКРЫЛ", 
        "G[A]Me[R]", 	
        "Kitty", 
        "EE",
        "Акива", 	
        "МOIIIK@", 
        "DeMpDeeZ", 	
        "FireBOY", 
        "InKey", 	
        "LeMoN", 
        "NedStreX", 	
        "Слеш", 
        "EVERALON", 	
        "Beаunty", 
        "Cherry Lips", 	
        "Essence", 
        "Frostk", 	
        "KoTuk kg", 
        "Kuki", 	
        "Link", 
        "Lixo", 	
        "Sting", 
        "WildHare", 	
        "Амон_ра", 
        "Aie", 	
        "Coco", 
        "Dark_Reaper", 	
        "Darz",	
        "MaJIeHKuu", 
        "MeLisa",
        "Miss Priss", 
        ":AnGeL:",
        "Algrinus",
        "AsmodeuZ",	
        "BaRsIk",
        "Daisy",
        "ext",
        "Fazer", 	
        "FlooMeer", 
        "Kisa",
        "LAS|SA", 	
        "Liona",
        "Mr.Agressor",	
        "rpuJlu",
        "RUFA",
        "Tekilla", 
        "Лапочка",	
        "Ballistic", 
        "Beretta",	
        "Black Look", 
        "Bumblebee",	
        "CyxarЬIk",
        "dazz",
        "ISTRIBITEL",
        "Kuku",
        "Mnika",	
        "adeon",
        "Mr_Dugles", 	
        "Piffy",
        "SkOrPiOnUs",	
        "SkyDeaD",
        "ZABY",
        "Агент",
        "AVANTGARDE",
        "Dark wolf", 
        "DragonStar", 	
        "Foxhaven", 
        "Gabby",	
        "Girmest", 
        "HITM@N",	
        "KiberTron", 
        "LeamuR", 	
        "Neadekvat", 
        "Shadw", 	
        "Канеки кен",
        "eByRaShKa", 	
        "Beautiful", 
        "BORODOTA", 	
        "Chilly", 
        "EnroKnights", 	
        "GrandRoyl", 
        "HeayHo", 	
        "HouruSinkara", 
        "Howfaralice", 	
        "HowlClaw", 
        "Iguana", 	
        "MoDiE", 
        "MonAmourKa", 	
        "Pudding", 
        "Reebok", 	
        "Каби",
        "Bambina", 
        "Dustup", 	
        "Forever", 
        "GameDevT",	
        "GhOsTiK", 
        "Main", 
        "xFaZe",
        "ANO",
        "Cred",
        "Dante",
        "Dimples", 	
        "GameMen",
        "MrThomas",	
        "NightKier",
        "SpeedBeast",	
        "TOUGH-_-GUY",
        "Эниси",
        "babnik",
        "Mau Mau",
        "Numnums",	
        "Artcross",
        "Bandz",
        "Mr.Pozitiv",
        "Flexiy",
        "Mitl"
    };

    public static string GenerateOneWordNick()
    {
        var nickName = oneWordNicks[Random.Range(0, oneWordNicks.Length)];
        return nickName;
    }
}

